#!/bin/bash
# check whether curl is installed
if ! command -v curl &> /dev/null; then
    echo "curl is not installed. Install curl to run this script."
    exit 1
fi

if [ -n "$1" ]; then
    INVOCATION_ID="$1"
    curl -X DELETE http://localhost:9070/invocations/${INVOCATION_ID}
else
    echo "supply invocation id"
fi