version: "3.3"
services:
  services:
    build:
      context: ../../services
    environment:
      - RESTATE_DEBUG_LOGGING=JOURNAL_VERBOSE
      - DATABASE_ENABLED=false

  jaeger:
    image: jaegertracing/all-in-one:1.47
    ports:
      - "16686:16686"
      - "4317:4317"
    environment:
      - COLLECTOR_OTLP_ENABLED=true

  runtime:
    image: docker.io/restatedev/restate:0.8
    depends_on:
      - services
      - jaeger
    ports:
      - "8080:8080"
      - "9070:9070"
      - "9071:9071"
    environment:
      - RUST_LOG=info,restate=debug
      - RESTATE_OBSERVABILITY__TRACING__ENDPOINT=http://jaeger:4317

  runtimesetup:
    image: alpine
    depends_on:
      - runtime
      - services
    restart: "no"
    volumes:
      - ../local/:/scripts
      - ../data/:/data
    entrypoint: ["sh", "-c", "sleep 5 && apk add --no-cache bash jq curl &&
    curl -X POST 'runtime:9070/deployments' -H 'content-type: application/json' -d '{\"uri\": \"http://services:9080\"}' &&
    sleep 3 && cd /scripts && chmod +x init_state.sh && ./init_state.sh runtime:8080
    || exit 1"]

  react_app:
    build:
      context: ../../react-shopping-cart
    depends_on:
      - runtimesetup
    ports:
      - "3000:3000"
