package my.example.cron;

import static com.cronutils.model.CronType.UNIX;

import com.cronutils.model.definition.CronDefinitionBuilder;
import com.cronutils.model.time.ExecutionTime;
import com.cronutils.parser.CronParser;
import dev.restate.common.Request;
import dev.restate.common.Target;
import dev.restate.sdk.Restate;
import dev.restate.sdk.annotation.*;
import dev.restate.sdk.common.StateKey;
import dev.restate.sdk.common.TerminalException;
import dev.restate.serde.TypeTag;
import java.time.ZonedDateTime;
import java.util.Optional;

/*
 * A distributed cron service built with Restate that schedules tasks based on cron expressions.
 *
 * Features:
 * - Create cron jobs with standard cron expressions (e.g., "0 0 * * *" for daily at midnight)
 * - Schedule any Restate service handler or virtual object method
 * - Guaranteed execution with Restate's durability
 * - Cancel and inspect running jobs
 *
 * Usage:
 * 1. Send requests to CronInitiator.create() to start new jobs
 * 2. Each job gets a unique ID and runs as a CronJob virtual object
 * 3. Jobs automatically reschedule themselves after each execution
 */
public class Cron {

  public record JobRequest(
      String cronExpression, // e.g. "0 0 * * *" (every day at midnight)
      String service,
      String method, // Handler to execute with this schedule
      Optional<String> key, // Optional Virtual Object key of the task to call
      Optional<String> payload) {} // Optional data to pass to the handler

  public record JobInfo(JobRequest request, String nextExecutionTime, String nextExecutionId) {}

  @Name("CronJobInitiator")
  @Service
  public static class JobInitiator {
    @Handler
    public String create(JobRequest request) {
      // Create a new job ID and initiate the cron job object for that ID
      // We can then address this job object by its ID
      var jobId = Restate.random().nextUUID().toString();
      var cronJob = Restate.virtualObject(Job.class, jobId).initiate(request);
      return String.format(
          "Job created with ID %s and next execution time %s", jobId, cronJob.nextExecutionTime());
    }
  }

  @Name("CronJob")
  @VirtualObject
  public static class Job {

    private final StateKey<JobInfo> JOB_STATE = StateKey.of("job-state", JobInfo.class);
    private final CronParser PARSER =
        new CronParser(CronDefinitionBuilder.instanceDefinitionFor(UNIX));

    @Handler
    public JobInfo initiate(JobRequest request) {
      if (Restate.state().get(JOB_STATE).isPresent()) {
        throw new TerminalException("Job already exists for this ID");
      }
      return scheduleNextExecution(request);
    }

    @Handler
    public void execute() {
      JobRequest request =
          Restate.state()
              .get(JOB_STATE)
              .orElseThrow(() -> new TerminalException("Job not found"))
              .request;

      executeTask(request);
      scheduleNextExecution(request);
    }

    @Handler
    public void cancel() {
      Restate.state()
          .get(JOB_STATE)
          .ifPresent(jobState -> Restate.invocationHandle(jobState.nextExecutionId).cancel());

      // Clear the job state
      Restate.state().clearAll();
    }

    @Shared
    public Optional<JobInfo> getInfo() {
      return Restate.state().get(JOB_STATE);
    }

    private void executeTask(JobRequest job) {
      Target target =
          (job.key.isPresent())
              ? Target.virtualObject(job.service, job.method, job.key.get())
              : Target.service(job.service, job.method);
      var request =
          (job.payload.isPresent())
              ? Request.of(
                  target, TypeTag.of(String.class), TypeTag.of(Void.class), job.payload.get())
              : Request.of(target, new byte[0]);
      Restate.send(request);
    }

    private JobInfo scheduleNextExecution(JobRequest request) {
      // Parse cron expression
      ExecutionTime executionTime;
      try {
        executionTime = ExecutionTime.forCron(PARSER.parse(request.cronExpression));
      } catch (IllegalArgumentException e) {
        throw new TerminalException("Invalid cron expression: " + e.getMessage());
      }

      // Calculate next execution time
      var now = Restate.run("now", ZonedDateTime.class, ZonedDateTime::now);
      var delay =
          executionTime
              .timeToNextExecution(now)
              .orElseThrow(() -> new TerminalException("Cannot determine next execution time"));
      var next =
          executionTime
              .nextExecution(now)
              .orElseThrow(() -> new TerminalException("Cannot determine next execution time"));

      // Schedule next execution for this job
      String thisJobId = Restate.key(); // This got generated by the CronJobInitiator
      var handle = Restate.virtualObjectHandle(Job.class, thisJobId).send(Job::execute, delay);

      // Save job state
      var jobState = new JobInfo(request, next.toString(), handle.invocationId());
      Restate.state().set(JOB_STATE, jobState);
      return jobState;
    }
  }
}
