#!/bin/bash

SCRIPTPATH="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"

docker build -t order-services:0.0.1 "$SCRIPTPATH/../app"  --secret id=npmrc,src=$HOME/.npmrc
docker build -t webui:0.0.1 "$SCRIPTPATH/../webui"
docker build -t restaurant-pos:0.0.1 "$SCRIPTPATH/../restaurant_pos"
