create table if not exists product (
       id varchar(255) not null,
        available_sizes text[],
        currency_format varchar(255),
        currency_id varchar(255),
        description varchar(255),
        is_free_shipping boolean,
        price_in_cents numeric not null,
        quantity int4 not null,
        sku int8,
        style varchar(255),
        title varchar(255),
        version_tag numeric not null,
        primary key (id)
);

insert into product(id, available_sizes, currency_format, currency_id, description, is_free_shipping, price_in_cents,
    quantity, sku, style, title, version_tag)
select p.id, p.available_sizes, p.currency_format, p.currency_id::varchar(255), p.description,
    p.is_free_shipping::varchar(255)::boolean, p.price_in_cents::numeric, p.quantity::int4, p.sku::int8, p.style,
    p.title, p.version_tag
from json_populate_recordset(null::product, '[
  {
    "available_sizes": ["X", "L", "XL", "XXL"],
    "currency_format": "$",
    "currency_id": "USD",
    "description": "14/15 s/nº",
    "id": 0,
    "quantity": 9,
    "is_free_shipping": true,
    "price_in_cents": 1090,
    "sku": 8552515751438644,
    "style": "White T-shirt",
    "title": "Cropped Stay Groovy off white",
    "version_tag": 0
  },
  {
    "available_sizes": ["X", "ML", "L"],
    "currency_format": "$",
    "currency_id": "USD",
    "description": "",
    "id": 11,
    "quantity": 3,
    "is_free_shipping": true,
    "price_in_cents": 1325,
    "sku": 39876704341265610,
    "style": "Wine",
    "title": "Basic Cactus White T-shirt",
    "version_tag": 0
  },
  {
    "available_sizes": ["XL"],
    "currency_format": "$",
    "currency_id": "USD",
    "description": "14/15 s/nº - Jogador",
    "id": 4,
    "quantity": 12,
    "is_free_shipping": false,
    "price_in_cents": 2590,
    "sku": 9197907543445676,
    "style": "Tony Hawk",
    "title": "Skater Black Sweatshirt",
    "version_tag": 0
  },
  {
    "available_sizes": ["M", "ML"],
    "currency_format": "$",
    "currency_id": "USD",
    "description": "",
    "id": 13,
    "quantity": 5,
    "is_free_shipping": true,
    "price_in_cents": 2945,
    "sku": 51498472915966370,
    "style": "Tule",
    "title": "Black Tule Oversized",
    "version_tag": 0
  },
  {
    "available_sizes": ["S", "XS"],
    "currency_format": "$",
    "currency_id": "USD",
    "description": "4 MSL",
    "id": 12,
    "quantity": 9,
    "is_free_shipping": true,
    "price_in_cents": 1090,
    "sku": 12064273040195392,
    "style": "Really Cool T-shirt",
    "title": "Black Batman T-shirt",
    "version_tag": 0
  },
  {
    "available_sizes": ["X", "L", "XL"],
    "currency_format": "$",
    "currency_id": "USD",
    "description": "GPX Poly 1",
    "id": 14,
    "quantity": 3,
    "is_free_shipping": true,
    "price_in_cents": 900,
    "sku": 10686354557628304,
    "style": "Mark Zuck have 365 of this one",
    "title": "Blue T-Shirt",
    "version_tag": 0
  },
  {
    "available_sizes": ["X", "L", "XL", "XXL"],
    "currency_format": "$",
    "currency_id": "USD",
    "description": "Treino 2014",
    "id": 15,
    "quantity": 5,
    "is_free_shipping": true,
    "price_in_cents": 1400,
    "sku": 11033926921508488,
    "style": "",
    "title": "Loose Black T-shirt",
    "version_tag": 0
  },
  {
    "available_sizes": ["X", "L", "XL", "XXL"],
    "currency_format": "$",
    "currency_id": "USD",
    "description": "14/15 s/nº",
    "id": 1,
    "quantity": 9,
    "is_free_shipping": true,
    "price_in_cents": 1090,
    "sku": 18644119330491310,
    "style": "White T-shirt",
    "title": "Ringer Hall Pass",
    "version_tag": 0
  },
  {
    "available_sizes": ["X", "L"],
    "currency_format": "$",
    "currency_id": "USD",
    "description": "14/15 s/nº",
    "id": 2,
    "quantity": 7,
    "is_free_shipping": true,
    "price_in_cents": 1490,
    "sku": 11854078013954528,
    "style": "You will like this one",
    "title": "Grey T-shirt",
    "version_tag": 0
  },
  {
    "available_sizes": ["X", "L"],
    "currency_format": "$",
    "currency_id": "USD",
    "description": "2014 s/nº",
    "id": 3,
    "quantity": 7,
    "is_free_shipping": true,
    "price_in_cents": 1490,
    "sku": 876661122392077,
    "style": "Adidas originals",
    "title": "Black T-shirt with white stripes",
    "version_tag": 0
  },
  {
    "available_sizes": ["X", "L", "XL"],
    "currency_format": "$",
    "currency_id": "USD",
    "description": "14/15 + Camiseta 1º Mundial",
    "id": 5,
    "quantity": 9,
    "is_free_shipping": false,
    "price_in_cents": 1090,
    "sku": 10547961582846888,
    "style": "Cowabunga!",
    "title": "Turtles Ninja T-shirt",
    "version_tag": 0
  },
  {
    "available_sizes": ["XL", "XXL"],
    "currency_format": "$",
    "currency_id": "USD",
    "description": "T-shirt 13/14",
    "id": 6,
    "quantity": 0,
    "is_free_shipping": true,
    "price_in_cents": 4990,
    "sku": 6090484789343891,
    "style": "When you wish well",
    "title": "Slim black T-shirt",
    "version_tag": 0
  },
  {
    "available_sizes": ["S"],
    "currency_format": "$",
    "currency_id": "USD",
    "description": "1977 Infantil",
    "id": 7,
    "quantity": 4,
    "is_free_shipping": true,
    "price_in_cents": 2250,
    "sku": 18532669286405344,
    "style": "Very comfy",
    "title": "Blue Sweatshirt",
    "version_tag": 0
  },
  {
    "available_sizes": ["XL"],
    "currency_format": "$",
    "currency_id": "USD",
    "description": "",
    "id": 8,
    "quantity": 4,
    "is_free_shipping": false,
    "price_in_cents": 1870,
    "sku": 5619496040738316,
    "style": "Girl the future is all your",
    "title": "White T-shirt Gucci",
    "version_tag": 0
  },
  {
    "available_sizes": ["L", "XL"],
    "currency_format": "$",
    "currency_id": "USD",
    "description": "",
    "id": 9,
    "quantity": 5,
    "is_free_shipping": true,
    "price_in_cents": 13490,
    "sku": 11600983276356164,
    "style": "",
    "title": "Tropical Wine T-shirt",
    "version_tag": 0
  },
  {
    "available_sizes": ["L", "XL"],
    "currency_format": "$",
    "currency_id": "USD",
    "description": "",
    "id": 10,
    "quantity": 9,
    "is_free_shipping": true,
    "price_in_cents": 4900,
    "sku": 27250082398145996,
    "style": "",
    "title": "Marine Blue T-shirt",
    "version_tag": 0
  }
]'::json) as p
on conflict do nothing;

