apiVersion: restate.dev/v1beta1
kind: RestateDeployment
metadata:
  name: service
spec:
  replicas: 1
  restate:
    register:
      cloud: my-cloud-env
    tunnelMode: in-process
  selector:
    matchLabels:
      app: service
  template:
    metadata:
      labels:
        app: service
    spec:
      containers:
        - name: service
          image: <registry>/my-restate-service:0.0.1
          env:
            - name: RESTATE_INPROC_AUTH_TOKEN_FILE
              value: /var/run/secrets/restate.cloud/token
          volumeMounts:
            - name: restate-cloud-tunnel-auth
              mountPath: /var/run/secrets/restate.cloud
              readOnly: true
      volumes:
        - name: restate-cloud-tunnel-auth
          secret:
            secretName: restate-cloud-tunnel-auth
