FROM python:3.11-slim

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 5000

ENV PYTHONPATH="/usr/src/app/src"
CMD ["flask", "--app", "restaurant/app:app", "run", "--host=0.0.0.0"]